### ISSUE TITLE
Build Your Own Device Instructions failed!

### ISSUE THREAD

**Issue by jzzxh** [samartzidis/magicstick.io#11]
Hi, @samartzidis 

I follow the " Build Your Own Device Instructions " but failed at step 3, The error message as following ..

![image](https://github.com/samartzidis/magicstick.io/assets/707605/327f5faa-68ab-42a6-bff8-f7554dac7578)

**Comment by samartzidis** [comment]
Hi @jzzxh, please make sure you are using the latest **magicstick-ui** utility from: https://github.com/samartzidis/magicstick.io/releases

**Comment by jzzxh** [comment]
HI @samartzidis , using the latest version no any pop up ui at  Initialize device option. OS: windows 11 pro. 21H2

**Comment by samartzidis** [comment]
Hi @jzzxh Thanks for pointing this out. Issue should be fixed in this release: https://github.com/samartzidis/magicstick.io/releases/tag/magicstick-ui.2.0.32
