### ISSUE TITLE
request for clarification in description

### ISSUE THREAD

**Issue by gtusr** [samartzidis/magicstick.io#2]
Assuming that all necessary pairings have already been made, can you clarify whether or not it is possible to use the magicstick in a mode where it is connected to *both* the keyboard and the PC over separate bluetooth connections at the same time, i.e. no cables needed?

**Comment by samartzidis** [comment]
Hi @gtusr. There is always a wired connection needed to the PC. So consider it a standard USB dongle in that respect. 

The side that connects to the keyboard though, can be wired (USB) or wireless (Bluetooth). When connected over wired connection, the keyboard is also charging.
