### ISSUE TITLE
Feature: Reconfigure right command as CTRL

### ISSUE THREAD

**Issue by Omnicrash** [samartzidis/magicstick.io#5]
For people that don't need right alt, it would be more useful to be able to configure right-command as a secondary CTRL key.

**Comment by samartzidis** [comment]
Provided you update your firmware to v2, you can map <kbd>Right Alt</kbd> to <kbd>Right Ctrl</kbd> by adding this rule at the end of the default keymap configuration:
`(mod & KEYBOARD_MODIFIER_RIGHTALT) && set_mod((mod & ~KEYBOARD_MODIFIER_RIGHTALT) | KEYBOARD_MODIFIER_RIGHTCTRL):end`

**Comment by Omnicrash** [comment]
Thanks for your continued effort, much appreciated!!
