### ISSUE TITLE
It's magicsick server is down? i can't install new firmware

### ISSUE THREAD

**Issue by jzzxh** [samartzidis/magicstick.io#7]

**Comment by samartzidis** [comment]
Hi @jzzxh, you need a physical magicstick.io device connected to your PC. Otherwise these options will be greyed out.

**Comment by jzzxh** [comment]
@samartzidis I bought an new pico W, how to get the firmware file? 
Thanks

**Comment by samartzidis** [comment]
Hi @jzzxh. As per the repository's main [README.md ](https://github.com/samartzidis/magicstick.io/blob/main/README.md) file, **magicstickUI** is the open-source and free Windows utility software, which provides the Windows software for controlling the **raspikey.io** device. However, the **raspikey.io** device itself is not free neither open-source and is not just a plain *Pico W* device. You purchase it separately and it comes pre-programmed with special firmware. So as you've already found out, a plain **Pico W** device will not work with the **magicstickUI** utility, as it lacks this special firmware. Hope that clarifies things and apologies for any confusion caused!

**Comment by samartzidis** [comment]
Hi @jzzxh, I do not offer a firmware download option at the moment I'm afraid. I can understand that it is a pain ordering a device from Etsy (it's also extra craft work for me) so I will think about setting something up for offering a download option for the few interested individuals - when I get the spare time. In the meantime, unfortunately, your only option is ordering a ready-made device.

**Comment by jzzxh** [comment]
HI, @samartzidis , OK, i got it. i'll waitting~~
Thanks.

**Comment by samartzidis** [comment]
FYI https://github.com/samartzidis/magicstick.io#option-2
