### ISSUE TITLE
Multimedia / function key mode choice

### ISSUE THREAD

**Issue by verityj** [samartzidis/magicstick.io#8]
By default, function key row cannot be modified and behaves as F1 through F12 with magicstick and A1644. Please let the user choose the Fn key behavior: either standard function keys or F1, F2 brightness, F7 - F12 multimedia keys.

On Windows 10 I do not have that choice in Windows Mobility Center.

Thank you!

**Comment by samartzidis** [comment]
https://github.com/samartzidis/magicstick.io/blob/main/release-notes.md#magicstick1146release54916d0
